### ISSUE TITLE
La fonction d'utilité

### ISSUE THREAD

**Issue by Aredli16** [Aredli16/tictactoe#9]
La fonction d'utilité doit accepter un plateau terminal en entrée et renvoyer l'utilité du plateau.
- Si X a gagné le jeu, l'utilité est de 1. Si O a gagné le jeu, l'utilité est de -1. Si le jeu s'est terminé par une égalité, l'utilité est de 0.
- Vous pouvez supposer que l

**Comment by ThomasDlx** [comment]
finish
